More fixes for Visual Studio.
Katana-Steel/lithtech pull request #58
Opened 2021-07-01 17:41 UTC by rohit-n

2021-07-03 08:37 UTC, Katana-Steel requested changes

2021-07-03 08:37 UTC, Katana-Steel commented on runtime/client/CMakeLists.txt
> -		${SDL2_INCLUDE_DIRS})
if you're hoisting the include dirs outside the platform specific section, please also bring out the `find_package(SDL2)` above

2021-07-03 08:37 UTC, Katana-Steel commented on CMakeLists.txt
> +endif(NOT WIN32)
please don't forget the newline at the end of the file

2021-07-08 17:43 UTC, rohit-n commented
Changes made.

2021-07-15 18:13 UTC, merged