Add toggle for windowed mode in Display Options.
Katana-Steel/lithtech pull request #82
Opened 2021-10-18 15:38 UTC by rohit-n

Taken from https://github.com/haekb/nolf2-modernizer/commit/6d8c6bd127a156745e6514cb88fcd1f8b5fe3258

2021-10-19 23:44 UTC, Katana-Steel requested changes

2021-10-19 23:44 UTC, Katana-Steel commented on NOLF2/ClientShellDLL/ClientShellShared/GameClientShell.cpp
> +		pProfile = g_pProfileMgr->GetCurrentProfile( );
does pProfile change between 1123 and here?
if not how about dropping this line?

2021-10-19 23:44 UTC, Katana-Steel commented on NOLF2/ClientShellDLL/ClientShellShared/GameClientShell.cpp
> +	SDL_Window* window;
move this to about or just before 1133

2021-10-19 23:44 UTC, Katana-Steel commented on NOLF2/ClientShellDLL/ClientShellShared/GameClientShell.cpp
> +	CUserProfile* pProfile;
just declare and initialize this on 1123, there's no need for it at the start of the function

2021-10-19 23:44 UTC, Katana-Steel commented on NOLF2/ClientShellDLL/ClientShellShared/ProfileMgr.cpp
> +	SDL_Window* window;
Again this can be moved to line 1120, window is not used anywhere else in the method

2021-10-20 22:20 UTC, rohit-n commented
Changes made.

2021-10-21 00:30 UTC, merged